input_raw_data = list(map(int, input().split(", ")))
positive = list(map(str,(filter(lambda x: x>=0, input_raw_data))))
negative = list(map(str,(filter(lambda x: x<0, input_raw_data))))
even = list(map(str, (filter(lambda x: x % 2 == 0, input_raw_data))))
odd = list(map(str, (filter(lambda x: x % 2 != 0, input_raw_data))))
print(f"Positive: {', '.join(positive)}")
print(f"Negative: {', '.join(negative)}")
print(f"Even: {', '.join(even)}")
print(f"Odd: {', '.join(odd)}")